name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Install dependencies
        run: npm install
        
      - name: Build static file
        run: npm run build

      - name: Deploy files
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '.git/*' --exclude '.github/*' --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
